- hosts: localhost
  tasks:
    - name: Request
      template:
        src: {{ SOURCE }}
        dest: {{ DEST }}
      tags: template
      register: template_output
    
    - debug: var=template_output